{
    'name': 'Z755 - Quản lý & đánh giá KPI',
    'version': '18.0.1.0.0',
    'category': 'Human Resources',
    'summary': 'Giao KPI, thực hiện, tự đánh giá, thẩm định, Tổ KPI, phê duyệt - pilot Ban CNTT',
    'description': 'Phân hệ KPI theo Đặc tả v1.2 (Z755): danh mục động, quy tắc chấm điểm cấu hình, '
                   'ảnh chụp, nhật ký thay đổi, quy trình đơn vị/cá nhân.',
    'author': 'Z755',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'hr'],
    'data': [
        'security/kpi_security.xml',
        'security/ir.model.access.csv',
        'security/kpi_rules.xml',
        'data/kpi_sequence.xml',
        'data/kpi_cron.xml',
        'data/kpi_seed.xml',
        'wizard/kpi_reason_wizard_views.xml',
        'views/kpi_period_views.xml',
        'views/kpi_catalog_views.xml',
        'views/kpi_rule_views.xml',
        'views/kpi_master_views.xml',
        'views/kpi_assignment_views.xml',
        'views/kpi_line_views.xml',
        'views/kpi_tracking_views.xml',
        'views/kpi_report_views.xml',
        'report/kpi_report.xml',
        'views/kpi_menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'z755_kpi/static/src/scss/kpi_theme.scss',
            'z755_kpi/static/src/js/*.js',
            'z755_kpi/static/src/xml/*.xml',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'application': True,
    'installable': True,
}
